# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MagmaRooms' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MagmaRooms
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Firestore'

  target 'MagmaRoomsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MagmaRooms-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MagmaRooms-tvOS

  target 'MagmaRooms-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
